# local_chat_calls.py
#########################################
# Local LLM API calls retained for compatibility with gateway-style providers.
#
####
import os
from typing import Any, Union, Dict, Optional, List, Callable

from tldw_Server_API.app.core.Chat.chat_service import perform_chat_api_call
from tldw_Server_API.app.core.LLM_Calls.deprecation import log_legacy_once
from tldw_Server_API.app.core.Utils.Utils import logging


####################
# Function List
# FIXME - UPDATE
# 1. chat_with_local_llm(text, custom_prompt_arg)
# 2. chat_with_llama(api_url, text, token, custom_prompt)
# 3. chat_with_kobold(api_url, text, kobold_api_token, custom_prompt)
# 4. chat_with_oobabooga(api_url, text, ooba_api_token, custom_prompt)
# 5. chat_with_vllm(vllm_api_url, vllm_api_key_function_arg, llm_model, text, vllm_custom_prompt_function_arg)
# 6. chat_with_tabbyapi(tabby_api_key, tabby_api_IP, text, tabby_model, custom_prompt)
# 7. save_summary_to_file(summary, file_path)
#
#
####################
# Import necessary libraries
# Import Local
#
#######################################################################################################################
# Function Definitions
#

def _call_adapter(
        provider: str,
        *,
        input_data: List[Dict[str, Any]],
        app_config: Optional[Dict[str, Any]] = None,
        **kwargs: Any,
) -> Any:
    log_legacy_once(
        "local_chat_calls",
        "local_chat_calls is deprecated; use chat_service.perform_chat_api_call instead.",
    )
    return perform_chat_api_call(
        api_provider=provider,
        messages=input_data,
        app_config=app_config,
        **kwargs,
    )


def chat_with_local_llm(
        input_data: List[Dict[str, Any]],
        temp: Optional[float] = None,
        temperature: Optional[float] = None,
        system_message: Optional[str] = None,
        streaming: Optional[bool] = None,
        stream: Optional[bool] = None,
        model: Optional[str] = None,
        top_k: Optional[int] = None,
        top_p: Optional[float] = None,
        min_p: Optional[float] = None,
        max_tokens: Optional[int] = None,
        seed: Optional[int] = None,
        stop: Optional[Union[str, List[str]]] = None,
        custom_prompt_arg: Optional[str] = None,
        response_format: Optional[Dict[str, str]] = None,
        n: Optional[int] = None,
        user_identifier: Optional[str] = None,
        logit_bias: Optional[Dict[str, float]] = None,
        presence_penalty: Optional[float] = None,
        frequency_penalty: Optional[float] = None,
        logprobs: Optional[bool] = None,
        top_logprobs: Optional[int] = None,
        tools: Optional[List[Dict[str, Any]]] = None,
        tool_choice: Optional[Union[str, Dict[str, Any]]] = None,
        app_config: Optional[Dict[str, Any]] = None,
        http_client_factory: Optional[Callable[[int], Any]] = None,
        http_fetcher: Optional[Callable[..., Any]] = None,
):
    return _call_adapter(
        "local-llm",
        input_data=input_data,
        temp=temp,
        temperature=temperature,
        system_message=system_message,
        streaming=streaming,
        stream=stream,
        model=model,
        top_k=top_k,
        top_p=top_p,
        min_p=min_p,
        max_tokens=max_tokens,
        seed=seed,
        stop=stop,
        custom_prompt_arg=custom_prompt_arg,
        response_format=response_format,
        n=n,
        user_identifier=user_identifier,
        logit_bias=logit_bias,
        presence_penalty=presence_penalty,
        frequency_penalty=frequency_penalty,
        logprobs=logprobs,
        top_logprobs=top_logprobs,
        tools=tools,
        tool_choice=tool_choice,
        app_config=app_config,
        http_client_factory=http_client_factory,
        http_fetcher=http_fetcher,
    )


def chat_with_llama(
        input_data: List[Dict[str, Any]],
        api_key: Optional[str] = None,
        custom_prompt: Optional[str] = None,
        temp: Optional[float] = None,
        temperature: Optional[float] = None,
        system_prompt: Optional[str] = None,
        streaming: Optional[bool] = None,
        stream: Optional[bool] = None,
        model: Optional[str] = None,
        top_k: Optional[int] = None,
        top_p: Optional[float] = None,
        min_p: Optional[float] = None,
        n_predict: Optional[int] = None,
        seed: Optional[int] = None,
        stop: Optional[Union[str, List[str]]] = None,
        response_format: Optional[Dict[str, str]] = None,
        logit_bias: Optional[Dict[str, float]] = None,
        n: Optional[int] = None,
        presence_penalty: Optional[float] = None,
        frequency_penalty: Optional[float] = None,
        api_url: Optional[str] = None,
        app_config: Optional[Dict[str, Any]] = None,
        http_client_factory: Optional[Callable[[int], Any]] = None,
        http_fetcher: Optional[Callable[..., Any]] = None,
):
    return _call_adapter(
        "llama.cpp",
        input_data=input_data,
        api_key=api_key,
        custom_prompt=custom_prompt,
        temp=temp,
        temperature=temperature,
        system_prompt=system_prompt,
        streaming=streaming,
        stream=stream,
        model=model,
        top_k=top_k,
        top_p=top_p,
        min_p=min_p,
        n_predict=n_predict,
        seed=seed,
        stop=stop,
        response_format=response_format,
        logit_bias=logit_bias,
        n=n,
        presence_penalty=presence_penalty,
        frequency_penalty=frequency_penalty,
        api_url=api_url,
        app_config=app_config,
        http_client_factory=http_client_factory,
        http_fetcher=http_fetcher,
    )


def chat_with_kobold(
        input_data: List[Dict[str, Any]],
        api_key: Optional[str] = None,
        custom_prompt_input: Optional[str] = None,
        temp: Optional[float] = None,
        system_message: Optional[str] = None,
        streaming: Optional[bool] = False,
        model: Optional[str] = None,
        top_k: Optional[int] = None,
        top_p: Optional[float] = None,
        max_length: Optional[int] = None,
        stop_sequence: Optional[Union[str, List[str]]] = None,
        num_responses: Optional[int] = None,
        seed: Optional[int] = None,
        app_config: Optional[Dict[str, Any]] = None,
):
    return _call_adapter(
        "kobold",
        input_data=input_data,
        api_key=api_key,
        custom_prompt_input=custom_prompt_input,
        temp=temp,
        system_message=system_message,
        streaming=streaming,
        model=model,
        top_k=top_k,
        top_p=top_p,
        max_length=max_length,
        stop_sequence=stop_sequence,
        num_responses=num_responses,
        seed=seed,
        app_config=app_config,
    )


def chat_with_oobabooga(
        input_data: List[Dict[str, Any]],
        api_key: Optional[str] = None,
        custom_prompt_input: Optional[str] = None,
        temp: Optional[float] = None,
        temperature: Optional[float] = None,
        system_message: Optional[str] = None,
        streaming: Optional[bool] = None,
        stream: Optional[bool] = None,
        model: Optional[str] = None,
        top_k: Optional[int] = None,
        top_p: Optional[float] = None,
        min_p: Optional[float] = None,
        max_tokens: Optional[int] = None,
        seed: Optional[int] = None,
        stop: Optional[Union[str, List[str]]] = None,
        response_format: Optional[Dict[str, str]] = None,
        n: Optional[int] = None,
        logit_bias: Optional[Dict[str, float]] = None,
        presence_penalty: Optional[float] = None,
        frequency_penalty: Optional[float] = None,
        logprobs: Optional[bool] = None,
        user_identifier: Optional[str] = None,
        tools: Optional[List[Dict[str, Any]]] = None,
        tool_choice: Optional[Union[str, Dict[str, Any]]] = None,
        top_logprobs: Optional[int] = None,
        ooba_api_url: Optional[str] = None,
        app_config: Optional[Dict[str, Any]] = None,
        http_client_factory: Optional[Callable[[int], Any]] = None,
        http_fetcher: Optional[Callable[..., Any]] = None,
):
    return _call_adapter(
        "ooba",
        input_data=input_data,
        api_key=api_key,
        custom_prompt_input=custom_prompt_input,
        temp=temp,
        temperature=temperature,
        system_message=system_message,
        streaming=streaming,
        stream=stream,
        model=model,
        top_k=top_k,
        top_p=top_p,
        min_p=min_p,
        max_tokens=max_tokens,
        seed=seed,
        stop=stop,
        response_format=response_format,
        n=n,
        logit_bias=logit_bias,
        presence_penalty=presence_penalty,
        frequency_penalty=frequency_penalty,
        logprobs=logprobs,
        user_identifier=user_identifier,
        tools=tools,
        tool_choice=tool_choice,
        top_logprobs=top_logprobs,
        ooba_api_url=ooba_api_url,
        app_config=app_config,
        http_client_factory=http_client_factory,
        http_fetcher=http_fetcher,
    )


def chat_with_tabbyapi(
        input_data: List[Dict[str, Any]],
        api_key: Optional[str] = None,
        custom_prompt_input: Optional[str] = None,
        temp: Optional[float] = None,
        temperature: Optional[float] = None,
        system_message: Optional[str] = None,
        streaming: Optional[bool] = None,
        stream: Optional[bool] = None,
        model: Optional[str] = None,
        top_k: Optional[int] = None,
        top_p: Optional[float] = None,
        min_p: Optional[float] = None,
        max_tokens: Optional[int] = None,
        seed: Optional[int] = None,
        stop: Optional[Union[str, List[str]]] = None,
        response_format: Optional[Dict[str, str]] = None,
        n: Optional[int] = None,
        logit_bias: Optional[Dict[str, float]] = None,
        presence_penalty: Optional[float] = None,
        frequency_penalty: Optional[float] = None,
        logprobs: Optional[bool] = None,
        user_identifier: Optional[str] = None,
        tools: Optional[List[Dict[str, Any]]] = None,
        tool_choice: Optional[Union[str, Dict[str, Any]]] = None,
        top_logprobs: Optional[int] = None,
        tabby_api_url: Optional[str] = None,
        app_config: Optional[Dict[str, Any]] = None,
        http_client_factory: Optional[Callable[[int], Any]] = None,
        http_fetcher: Optional[Callable[..., Any]] = None,
):
    return _call_adapter(
        "tabbyapi",
        input_data=input_data,
        api_key=api_key,
        custom_prompt_input=custom_prompt_input,
        temp=temp,
        temperature=temperature,
        system_message=system_message,
        streaming=streaming,
        stream=stream,
        model=model,
        top_k=top_k,
        top_p=top_p,
        min_p=min_p,
        max_tokens=max_tokens,
        seed=seed,
        stop=stop,
        response_format=response_format,
        n=n,
        logit_bias=logit_bias,
        presence_penalty=presence_penalty,
        frequency_penalty=frequency_penalty,
        logprobs=logprobs,
        user_identifier=user_identifier,
        tools=tools,
        tool_choice=tool_choice,
        top_logprobs=top_logprobs,
        tabby_api_url=tabby_api_url,
        app_config=app_config,
        http_client_factory=http_client_factory,
        http_fetcher=http_fetcher,
    )


def chat_with_vllm(
        input_data: List[Dict[str, Any]],
        api_key: Optional[str] = None,
        custom_prompt_input: Optional[str] = None,
        temp: Optional[float] = None,
        temperature: Optional[float] = None,
        system_prompt: Optional[str] = None,
        streaming: Optional[bool] = None,
        stream: Optional[bool] = None,
        model: Optional[str] = None,
        top_k: Optional[int] = None,
        top_p: Optional[float] = None,
        min_p: Optional[float] = None,
        max_tokens: Optional[int] = None,
        seed: Optional[int] = None,
        stop: Optional[Union[str, List[str]]] = None,
        response_format: Optional[Dict[str, str]] = None,
        n: Optional[int] = None,
        logit_bias: Optional[Dict[str, float]] = None,
        presence_penalty: Optional[float] = None,
        frequency_penalty: Optional[float] = None,
        logprobs: Optional[bool] = None,
        user_identifier: Optional[str] = None,
        tools: Optional[List[Dict[str, Any]]] = None,
        tool_choice: Optional[Union[str, Dict[str, Any]]] = None,
        top_logprobs: Optional[int] = None,
        vllm_api_url: Optional[str] = None,
        app_config: Optional[Dict[str, Any]] = None,
        http_client_factory: Optional[Callable[[int], Any]] = None,
        http_fetcher: Optional[Callable[..., Any]] = None,
):
    return _call_adapter(
        "vllm",
        input_data=input_data,
        api_key=api_key,
        custom_prompt_input=custom_prompt_input,
        temp=temp,
        temperature=temperature,
        system_prompt=system_prompt,
        streaming=streaming,
        stream=stream,
        model=model,
        top_k=top_k,
        top_p=top_p,
        min_p=min_p,
        max_tokens=max_tokens,
        seed=seed,
        stop=stop,
        response_format=response_format,
        n=n,
        logit_bias=logit_bias,
        presence_penalty=presence_penalty,
        frequency_penalty=frequency_penalty,
        logprobs=logprobs,
        user_identifier=user_identifier,
        tools=tools,
        tool_choice=tool_choice,
        top_logprobs=top_logprobs,
        vllm_api_url=vllm_api_url,
        app_config=app_config,
        http_client_factory=http_client_factory,
        http_fetcher=http_fetcher,
    )


def chat_with_aphrodite(
        input_data: List[Dict[str, Any]],
        api_key: Optional[str] = None,
        custom_prompt_input: Optional[str] = None,
        temp: Optional[float] = None,
        temperature: Optional[float] = None,
        system_prompt: Optional[str] = None,
        streaming: Optional[bool] = None,
        stream: Optional[bool] = None,
        model: Optional[str] = None,
        top_k: Optional[int] = None,
        top_p: Optional[float] = None,
        min_p: Optional[float] = None,
        max_tokens: Optional[int] = None,
        seed: Optional[int] = None,
        stop: Optional[Union[str, List[str]]] = None,
        response_format: Optional[Dict[str, str]] = None,
        n: Optional[int] = None,
        logit_bias: Optional[Dict[str, float]] = None,
        presence_penalty: Optional[float] = None,
        frequency_penalty: Optional[float] = None,
        logprobs: Optional[bool] = None,
        user_identifier: Optional[str] = None,
        tools: Optional[List[Dict[str, Any]]] = None,
        tool_choice: Optional[Union[str, Dict[str, Any]]] = None,
        top_logprobs: Optional[int] = None,
        aphrodite_api_url: Optional[str] = None,
        app_config: Optional[Dict[str, Any]] = None,
        http_client_factory: Optional[Callable[[int], Any]] = None,
        http_fetcher: Optional[Callable[..., Any]] = None,
):
    return _call_adapter(
        "aphrodite",
        input_data=input_data,
        api_key=api_key,
        custom_prompt_input=custom_prompt_input,
        temp=temp,
        temperature=temperature,
        system_prompt=system_prompt,
        streaming=streaming,
        stream=stream,
        model=model,
        top_k=top_k,
        top_p=top_p,
        min_p=min_p,
        max_tokens=max_tokens,
        seed=seed,
        stop=stop,
        response_format=response_format,
        n=n,
        logit_bias=logit_bias,
        presence_penalty=presence_penalty,
        frequency_penalty=frequency_penalty,
        logprobs=logprobs,
        user_identifier=user_identifier,
        tools=tools,
        tool_choice=tool_choice,
        top_logprobs=top_logprobs,
        aphrodite_api_url=aphrodite_api_url,
        app_config=app_config,
        http_client_factory=http_client_factory,
        http_fetcher=http_fetcher,
    )


def chat_with_ollama(
        input_data: List[Dict[str, Any]],
        api_key: Optional[str] = None,
        custom_prompt: Optional[str] = None,
        temp: Optional[float] = None,
        temperature: Optional[float] = None,
        system_message: Optional[str] = None,
        streaming: Optional[bool] = None,
        stream: Optional[bool] = None,
        model: Optional[str] = None,
        top_k: Optional[int] = None,
        top_p: Optional[float] = None,
        min_p: Optional[float] = None,
        max_tokens: Optional[int] = None,
        seed: Optional[int] = None,
        stop: Optional[Union[str, List[str]]] = None,
        response_format: Optional[Dict[str, str]] = None,
        n: Optional[int] = None,
        logit_bias: Optional[Dict[str, float]] = None,
        presence_penalty: Optional[float] = None,
        frequency_penalty: Optional[float] = None,
        logprobs: Optional[bool] = None,
        user_identifier: Optional[str] = None,
        tools: Optional[List[Dict[str, Any]]] = None,
        tool_choice: Optional[Union[str, Dict[str, Any]]] = None,
        top_logprobs: Optional[int] = None,
        app_config: Optional[Dict[str, Any]] = None,
        http_client_factory: Optional[Callable[[int], Any]] = None,
        http_fetcher: Optional[Callable[..., Any]] = None,
):
    return _call_adapter(
        "ollama",
        input_data=input_data,
        api_key=api_key,
        custom_prompt=custom_prompt,
        temp=temp,
        temperature=temperature,
        system_message=system_message,
        streaming=streaming,
        stream=stream,
        model=model,
        top_k=top_k,
        top_p=top_p,
        min_p=min_p,
        max_tokens=max_tokens,
        seed=seed,
        stop=stop,
        response_format=response_format,
        n=n,
        logit_bias=logit_bias,
        presence_penalty=presence_penalty,
        frequency_penalty=frequency_penalty,
        logprobs=logprobs,
        user_identifier=user_identifier,
        tools=tools,
        tool_choice=tool_choice,
        top_logprobs=top_logprobs,
        app_config=app_config,
        http_client_factory=http_client_factory,
        http_fetcher=http_fetcher,
    )


def chat_with_custom_openai(
    input_data: List[Dict[str, Any]],
    api_key: Optional[str] = None,
    custom_prompt_arg: Optional[str] = None,
    temp: Optional[float] = None,
    system_message: Optional[str] = None,
    streaming: Optional[bool] = False,
    model: Optional[str] = None,
    maxp: Optional[float] = None,
    topp: Optional[float] = None,
    minp: Optional[float] = None,
    topk: Optional[int] = None,
    max_tokens: Optional[int] = None,
    seed: Optional[int] = None,
    stop: Optional[Union[str, List[str]]] = None,
    response_format: Optional[Dict[str, str]] = None,
    n: Optional[int] = None,
    user_identifier: Optional[str] = None,
    tools: Optional[List[Dict[str, Any]]] = None,
    tool_choice: Optional[Union[str, Dict[str, Any]]] = None,
    logit_bias: Optional[Dict[str, float]] = None,
    presence_penalty: Optional[float] = None,
    frequency_penalty: Optional[float] = None,
    logprobs: Optional[bool] = None,
    top_logprobs: Optional[int] = None,
    app_config: Optional[Dict[str, Any]] = None,
    http_client_factory: Optional[Callable[[int], Any]] = None,
    http_fetcher: Optional[Callable[..., Any]] = None,
):
    return _call_adapter(
        "custom-openai-api",
        input_data=input_data,
        api_key=api_key,
        custom_prompt_arg=custom_prompt_arg,
        temp=temp,
        system_message=system_message,
        streaming=streaming,
        model=model,
        maxp=maxp,
        topp=topp,
        minp=minp,
        topk=topk,
        max_tokens=max_tokens,
        seed=seed,
        stop=stop,
        response_format=response_format,
        n=n,
        user_identifier=user_identifier,
        tools=tools,
        tool_choice=tool_choice,
        logit_bias=logit_bias,
        presence_penalty=presence_penalty,
        frequency_penalty=frequency_penalty,
        logprobs=logprobs,
        top_logprobs=top_logprobs,
        app_config=app_config,
        http_client_factory=http_client_factory,
        http_fetcher=http_fetcher,
    )


def chat_with_custom_openai_2(
    input_data: List[Dict[str, Any]],
    api_key: Optional[str] = None,
    custom_prompt_arg: Optional[str] = None,
    temp: Optional[float] = None,
    system_message: Optional[str] = None,
    streaming: Optional[bool] = False,
    model: Optional[str] = None,
    max_tokens: Optional[int] = None,
    topp: Optional[float] = None,
    seed: Optional[int] = None,
    stop: Optional[Union[str, List[str]]] = None,
    response_format: Optional[Dict[str, str]] = None,
    n: Optional[int] = None,
    user_identifier: Optional[str] = None,
    tools: Optional[List[Dict[str, Any]]] = None,
    tool_choice: Optional[Union[str, Dict[str, Any]]] = None,
    logit_bias: Optional[Dict[str, float]] = None,
    presence_penalty: Optional[float] = None,
    frequency_penalty: Optional[float] = None,
    logprobs: Optional[bool] = None,
    top_logprobs: Optional[int] = None,
    app_config: Optional[Dict[str, Any]] = None,
    http_client_factory: Optional[Callable[[int], Any]] = None,
    http_fetcher: Optional[Callable[..., Any]] = None,
):
    return _call_adapter(
        "custom-openai-api-2",
        input_data=input_data,
        api_key=api_key,
        custom_prompt_arg=custom_prompt_arg,
        temp=temp,
        system_message=system_message,
        streaming=streaming,
        model=model,
        max_tokens=max_tokens,
        topp=topp,
        seed=seed,
        stop=stop,
        response_format=response_format,
        n=n,
        user_identifier=user_identifier,
        tools=tools,
        tool_choice=tool_choice,
        logit_bias=logit_bias,
        presence_penalty=presence_penalty,
        frequency_penalty=frequency_penalty,
        logprobs=logprobs,
        top_logprobs=top_logprobs,
        app_config=app_config,
        http_client_factory=http_client_factory,
        http_fetcher=http_fetcher,
    )


def save_summary_to_file(summary: str, file_path: str):  # Type hinting
    logging.debug("Now saving summary to file...")
    summary_file_path: Optional[str] = None
    try:
        base_name = os.path.splitext(os.path.basename(file_path))[0]
        # Ensure the path is safe and within an expected directory if necessary
        summary_file_path = os.path.join(os.path.dirname(file_path), base_name + '_summary.txt')
        os.makedirs(os.path.dirname(summary_file_path), exist_ok=True)
        logging.debug(f"Opening summary file for writing: {summary_file_path}")
        with open(summary_file_path, 'w', encoding='utf-8') as file:  # Added encoding
            file.write(summary)
        logging.info(f"Summary saved to file: {summary_file_path}")
    except Exception as e:
        # Guard against UnboundLocalError if failure occurs before summary_file_path assignment
        target = summary_file_path or file_path
        logging.error(f"Error saving summary to file '{target}': {e}", exc_info=True)
        # Depending on context, might want to re-raise or handle

#
#
#######################################################################################################################
