"""Personalization helpers and adapter utilities."""

from tldw_Server_API.app.core.Personalization.companion_activity import (
    record_companion_activity,
    record_note_created,
    record_note_deleted,
    record_note_restored,
    record_note_updated,
    record_persona_session_started,
    record_persona_session_summarized,
    record_persona_tool_executed,
    record_reading_highlight_created,
    record_reading_highlight_deleted,
    record_reading_highlight_updated,
    record_reminder_task_created,
    record_reminder_task_deleted,
    record_reminder_task_updated,
    record_reading_item_archived,
    record_reading_item_deleted,
    record_reading_note_linked,
    record_reading_note_unlinked,
    record_reading_item_saved,
    record_reading_item_updated,
    record_watchlist_source_created,
    record_watchlist_source_deleted,
    record_watchlist_source_restored,
    record_watchlist_source_updated,
)
from tldw_Server_API.app.core.Personalization.companion_context import load_companion_context
from tldw_Server_API.app.core.Personalization.companion_derivations import derive_companion_knowledge_cards

__all__ = [
    "record_companion_activity",
    "load_companion_context",
    "derive_companion_knowledge_cards",
    "record_note_created",
    "record_note_deleted",
    "record_note_restored",
    "record_note_updated",
    "record_persona_session_started",
    "record_persona_session_summarized",
    "record_persona_tool_executed",
    "record_reading_highlight_created",
    "record_reading_highlight_deleted",
    "record_reading_highlight_updated",
    "record_reminder_task_created",
    "record_reminder_task_deleted",
    "record_reminder_task_updated",
    "record_reading_item_archived",
    "record_reading_item_deleted",
    "record_reading_note_linked",
    "record_reading_note_unlinked",
    "record_reading_item_saved",
    "record_reading_item_updated",
    "record_watchlist_source_created",
    "record_watchlist_source_deleted",
    "record_watchlist_source_restored",
    "record_watchlist_source_updated",
]
