"""Generate sidecar worker configs and docs from a manifest."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence


@dataclass(frozen=True)
class Worker:
    key: str
    slug: str
    label: str
    module: str
    optional: bool


REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST_PATH = REPO_ROOT / "Docs/Deployment/sidecar_workers_manifest.json"
TEMPLATE_PATH = REPO_ROOT / "Docs/Deployment/Sidecar_Workers.template.md"

DOC_OUTPUTS = (
    REPO_ROOT / "Docs/Deployment/Sidecar_Workers.md",
    REPO_ROOT / "Docs/Published/Deployment/Sidecar_Workers.md",
)

SYSTEMD_DIRS = (
    REPO_ROOT / "Docs/Deployment/systemd",
    REPO_ROOT / "Docs/Published/Deployment/systemd",
)

LAUNCHD_DIRS = (
    REPO_ROOT / "Docs/Deployment/launchd",
    REPO_ROOT / "Docs/Published/Deployment/launchd",
)

COMPOSE_PATH = REPO_ROOT / "Dockerfiles/docker-compose.workers.yml"

GENERATED_NOTICE = (
    "Generated by Helper_Scripts/Deployment/generate_sidecar_files.py. "
    "Edit Docs/Deployment/sidecar_workers_manifest.json and "
    "Docs/Deployment/Sidecar_Workers.template.md."
)


SYSTEMD_SERVICE_TEMPLATE = """# {notice}
[Unit]
Description=tldw worker: {label}
After=network.target
Wants=network.target

[Service]
Type=simple
User=tldw
Group=tldw
WorkingDirectory=/opt/tldw_server
EnvironmentFile=-/etc/tldw/tldw.env
Environment=PYTHONUNBUFFERED=1
ExecStart=/opt/tldw_server/.venv/bin/python -m {module}
Restart=always
RestartSec=5
KillSignal=SIGINT
TimeoutStopSec=30

[Install]
WantedBy=multi-user.target
"""

SYSTEMD_TIMER_TEMPLATE = """# {notice}
[Unit]
Description=Ensure tldw worker ({slug}) is running

[Timer]
OnBootSec=30s
OnUnitActiveSec=5m
Unit=tldw-worker-{slug}.service
Persistent=true

[Install]
WantedBy=timers.target
"""

LAUNCHD_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- {notice} -->
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.tldw.worker.{slug}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/opt/tldw_server/.venv/bin/python</string>
    <string>-m</string>
    <string>{module}</string>
  </array>
  <key>WorkingDirectory</key>
  <string>/opt/tldw_server</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PYTHONUNBUFFERED</key>
    <string>1</string>
  </dict>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>/opt/tldw_server/logs/launchd/{slug}.log</string>
  <key>StandardErrorPath</key>
  <string>/opt/tldw_server/logs/launchd/{slug}.err.log</string>
</dict>
</plist>
"""


def _load_manifest(path: Path) -> tuple[list[Worker], list[str]]:
    if not path.exists():
        raise FileNotFoundError(f"Missing manifest: {path}")

    data = json.loads(path.read_text())
    default_workers = data.get("default_workers")
    workers_data = data.get("workers")

    if not isinstance(default_workers, list):
        raise ValueError("default_workers must be a list")
    if not isinstance(workers_data, list):
        raise ValueError("workers must be a list")

    workers: list[Worker] = []
    keys = set()
    slugs = set()

    for item in workers_data:
        if not isinstance(item, dict):
            raise ValueError("Each worker must be an object")
        key = item.get("key")
        slug = item.get("slug")
        label = item.get("label")
        module = item.get("module")
        optional = bool(item.get("optional", False))

        if not all(isinstance(field, str) and field for field in (key, slug, label, module)):
            raise ValueError(f"Invalid worker entry: {item}")
        if key in keys:
            raise ValueError(f"Duplicate worker key: {key}")
        if slug in slugs:
            raise ValueError(f"Duplicate worker slug: {slug}")

        keys.add(key)
        slugs.add(slug)
        workers.append(Worker(key=key, slug=slug, label=label, module=module, optional=optional))

    missing = [name for name in default_workers if name not in keys]
    if missing:
        raise ValueError(f"default_workers missing entries: {missing}")

    return workers, list(default_workers)


def _clean_dir(path: Path, patterns: Iterable[str]) -> None:
    path.mkdir(parents=True, exist_ok=True)
    for pattern in patterns:
        for entry in path.glob(pattern):
            entry.unlink()


def _render_docs(template_path: Path, workers: Sequence[Worker], default_workers: Sequence[str]) -> str:
    template = template_path.read_text()
    worker_lines = []
    for worker in workers:
        suffix = " (optional)" if worker.optional else ""
        worker_lines.append(f"- {worker.label}{suffix}: `python -m {worker.module}`")

    optional_keys = [worker.key for worker in workers if worker.optional]
    if optional_keys:
        optional_note = f"  (add {', '.join(optional_keys)} if you use those jobs)"
    else:
        optional_note = ""

    content = (
        template.replace("{{WORKER_LIST}}", "\n".join(worker_lines))
        .replace("{{DEFAULT_WORKERS}}", ",".join(default_workers))
        .replace("{{OPTIONAL_NOTE}}", optional_note)
    )
    return f"<!-- {GENERATED_NOTICE} -->\n{content}"


def _render_compose(workers: Sequence[Worker]) -> str:
    lines = [
        f"# {GENERATED_NOTICE}",
        "# docker-compose.workers.yml",
        "# Sidecar Jobs workers for the core API stack.",
        "# Use with the base compose file:",
        "#   docker compose -f Dockerfiles/docker-compose.yml -f Dockerfiles/docker-compose.workers.yml up -d --build",
        "",
        "x-worker-env: &worker-env",
        "  AUTH_MODE: ${AUTH_MODE:-single_user}",
        "  SINGLE_USER_API_KEY: ${SINGLE_USER_API_KEY:-change-me}",
        "  tldw_production: ${tldw_production:-false}",
        "  DATABASE_URL: ${DATABASE_URL:-sqlite:///./Databases/users.db}",
        "  JOBS_DB_URL: ${JOBS_DB_URL:-}",
        "  REDIS_URL: ${REDIS_URL:-redis://redis:6379}",
        "  LOG_LEVEL: ${LOG_LEVEL:-info}",
        "",
        "x-worker-base: &worker-base",
        "  build:",
        "    context: ..",
        "    dockerfile: Dockerfiles/Dockerfile.prod",
        "  image: tldw-server:prod",
        "  restart: unless-stopped",
        "  depends_on:",
        "    - postgres",
        "    - redis",
        "  environment: *worker-env",
        "  volumes:",
        "    - app-data:/app/Databases",
        "    - chroma-data:/app/Databases/user_databases",
        "",
        "services:",
        "  app:",
        "    environment:",
        "      - TLDW_WORKERS_SIDECAR_MODE=true",
        "",
    ]

    for worker in workers:
        if worker.optional:
            lines.append("  # optional")
        lines.extend(
            [
                f"  worker-{worker.slug}:",
                "    <<: *worker-base",
                f"    container_name: tldw-worker-{worker.slug}",
                f"    command: python -m {worker.module}",
                "",
            ]
        )

    return "\n".join(lines).rstrip() + "\n"


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def main() -> int:
    workers, default_workers = _load_manifest(MANIFEST_PATH)

    docs_content = _render_docs(TEMPLATE_PATH, workers, default_workers)
    for doc_path in DOC_OUTPUTS:
        _write_text(doc_path, docs_content)

    for systemd_dir in SYSTEMD_DIRS:
        _clean_dir(systemd_dir, ("tldw-worker-*.service", "tldw-worker-*.timer"))
        for worker in workers:
            service_path = systemd_dir / f"tldw-worker-{worker.slug}.service"
            timer_path = systemd_dir / f"tldw-worker-{worker.slug}.timer"
            _write_text(
                service_path,
                SYSTEMD_SERVICE_TEMPLATE.format(
                    notice=GENERATED_NOTICE,
                    label=worker.label,
                    module=worker.module,
                ),
            )
            _write_text(
                timer_path,
                SYSTEMD_TIMER_TEMPLATE.format(
                    notice=GENERATED_NOTICE,
                    slug=worker.slug,
                ),
            )

    for launchd_dir in LAUNCHD_DIRS:
        _clean_dir(launchd_dir, ("com.tldw.worker.*.plist",))
        for worker in workers:
            plist_path = launchd_dir / f"com.tldw.worker.{worker.slug}.plist"
            _write_text(
                plist_path,
                LAUNCHD_TEMPLATE.format(
                    notice=GENERATED_NOTICE,
                    slug=worker.slug,
                    module=worker.module,
                ),
            )

    _write_text(COMPOSE_PATH, _render_compose(workers))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
