#!/usr/bin/env bash
# quickstart.sh - One-liner setup for tldw_server
#
# Usage:
#   ./Helper_Scripts/quickstart.sh
#   # or from anywhere:
#   curl -sL https://raw.githubusercontent.com/rmusser01/tldw_server/main/Helper_Scripts/quickstart.sh | bash
#
# This script:
#   1. Generates a secure API key (if not provided)
#   2. Creates a minimal .env file
#   3. Runs AuthNZ initialization (non-interactive)
#   4. Prints next steps

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "=== tldw_server Quickstart ==="
echo ""

# Check Python version
PYTHON_VERSION=$(python3 --version 2>&1 | cut -d' ' -f2)
PYTHON_MAJOR=$(echo "$PYTHON_VERSION" | cut -d. -f1)
PYTHON_MINOR=$(echo "$PYTHON_VERSION" | cut -d. -f2)

if [[ "$PYTHON_MAJOR" -lt 3 ]] || [[ "$PYTHON_MAJOR" -eq 3 && "$PYTHON_MINOR" -lt 10 ]]; then
    echo "Error: Python 3.10+ required (found $PYTHON_VERSION)"
    exit 1
fi
echo "[OK] Python $PYTHON_VERSION"

# Check ffmpeg
if ! command -v ffmpeg &> /dev/null; then
    echo "Warning: ffmpeg not found. Audio/video processing will not work."
    echo "  Install: brew install ffmpeg (macOS) or apt install ffmpeg (Linux)"
else
    echo "[OK] ffmpeg found"
fi

# Generate or use existing API key
if [[ -n "${SINGLE_USER_API_KEY:-}" ]]; then
    API_KEY="$SINGLE_USER_API_KEY"
    echo "[OK] Using provided SINGLE_USER_API_KEY"
else
    # Generate a secure random key (32 bytes, base64 encoded = ~43 chars)
    if command -v openssl &> /dev/null; then
        API_KEY=$(openssl rand -base64 32 | tr -d '\n')
    else
        # Fallback to Python
        API_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
    fi
    echo "[OK] Generated secure API key"
fi

# Create .env if it doesn't exist
cd "$REPO_ROOT"
if [[ -f .env ]]; then
    echo "[OK] .env already exists (not overwriting)"
else
    cat > .env << EOF
# tldw_server configuration (generated by quickstart.sh)
AUTH_MODE=single_user
SINGLE_USER_API_KEY=$API_KEY
DATABASE_URL=sqlite:///./Databases/users.db

# Optional: Add your LLM provider keys
# OPENAI_API_KEY=sk-...
# ANTHROPIC_API_KEY=sk-ant-...
EOF
    echo "[OK] Created .env"
fi

# Run AuthNZ initialization
echo ""
echo "Initializing authentication..."
python3 -m tldw_Server_API.app.core.AuthNZ.initialize --non-interactive
echo "[OK] Auth initialized"

# Print summary
echo ""
echo "=== Setup Complete ==="
echo ""
echo "Your API key: $API_KEY"
echo ""
echo "Next steps:"
echo "  1. Start the server:"
echo "     uvicorn tldw_Server_API.app.main:app --host 127.0.0.1 --port 8000"
echo ""
echo "  2. Verify it works (no auth needed):"
echo "     curl http://localhost:8000/health"
echo ""
echo "  3. Test with your API key:"
echo "     curl -H 'X-API-KEY: $API_KEY' http://localhost:8000/api/v1/llm/providers"
echo ""
echo "  4. Open the API docs:"
echo "     http://localhost:8000/docs"
echo ""
echo "Or use: make quickstart (starts server automatically)"
