"""Workflow adapters submodule.

This module provides a decorator-based registry system for workflow step adapters.
All adapters are registered during import and can be looked up by step type name.

Usage:
    from tldw_Server_API.app.core.Workflows.adapters import get_adapter, registry

    # Get an adapter by name
    adapter = get_adapter("llm")
    if adapter:
        result = await adapter(config, context)

    # Get all parallelizable adapter names
    parallel_adapters = get_parallelizable()

    # Get the full catalog
    catalog = registry.get_catalog()
"""

from tldw_Server_API.app.core.Workflows.adapters._registry import (
    registry,
    get_adapter,
    get_parallelizable,
    AdapterSpec,
    AdapterRegistry,
)
from tldw_Server_API.app.core.Workflows.adapters._base import (
    AdapterContext,
    BaseAdapterConfig,
    AdapterFunc,
    AdapterResult,
)
from tldw_Server_API.app.core.Workflows.adapters._common import (
    extract_openai_content,
    sanitize_path_component,
    is_subpath,
    resolve_context_user_id,
    artifacts_base_dir,
    resolve_artifacts_dir,
    resolve_artifact_filename,
    unsafe_file_access_allowed,
    workflow_file_base_dir,
    resolve_workflow_file_path,
    resolve_workflow_file_uri,
    normalize_str_list,
    extract_mcp_policy,
    tool_matches_allowlist,
    extract_tool_scopes,
    format_time_srt,
    format_time_vtt,
    # Backward compatible underscore-prefixed aliases
    _extract_openai_content,
    _sanitize_path_component,
    _is_subpath,
    _resolve_context_user_id,
    _artifacts_base_dir,
    _resolve_artifacts_dir,
    _resolve_artifact_filename,
    _unsafe_file_access_allowed,
    _workflow_file_base_dir,
    _resolve_workflow_file_path,
    _resolve_workflow_file_uri,
    _normalize_str_list,
    _extract_mcp_policy,
    _tool_matches_allowlist,
    _extract_tool_scopes,
    _format_time_srt,
    _format_time_vtt,
)

# Import migrated category modules to register their adapters
# Each module's import triggers the @registry.register decorators
from tldw_Server_API.app.core.Workflows.adapters import control
from tldw_Server_API.app.core.Workflows.adapters import llm

# Import stub modules for categories not yet fully migrated
from tldw_Server_API.app.core.Workflows.adapters import audio
from tldw_Server_API.app.core.Workflows.adapters import video
from tldw_Server_API.app.core.Workflows.adapters import media
from tldw_Server_API.app.core.Workflows.adapters import rag
from tldw_Server_API.app.core.Workflows.adapters import knowledge
from tldw_Server_API.app.core.Workflows.adapters import content
from tldw_Server_API.app.core.Workflows.adapters import text
from tldw_Server_API.app.core.Workflows.adapters import integration
from tldw_Server_API.app.core.Workflows.adapters import evaluation
from tldw_Server_API.app.core.Workflows.adapters import research
from tldw_Server_API.app.core.Workflows.adapters import utility

# Register legacy adapters that haven't been migrated yet
from tldw_Server_API.app.core.Workflows.adapters._legacy_bridge import register_legacy_adapters
register_legacy_adapters(registry)

# Re-export exceptions and internal module references for backward compatibility
from tldw_Server_API.app.core.exceptions import AdapterError
from tldw_Server_API.app.core.http_client import create_client as _wf_create_client
import asyncio  # Re-export for tests that patch adapters.asyncio

# Re-export all adapter functions for backward compatibility
# This allows existing code to import like: from ...adapters import run_llm_adapter
from tldw_Server_API.app.core.Workflows._adapters_legacy import (
    run_llm_adapter,
    run_prompt_adapter,
    run_rag_search_adapter,
    run_media_ingest_adapter,
    run_mcp_tool_adapter,
    run_webhook_adapter,
    run_tts_adapter,
    run_process_media_adapter,
    run_branch_adapter,
    run_map_adapter,
    run_delay_adapter,
    run_log_adapter,
    run_policy_check_adapter,
    run_rss_fetch_adapter,
    run_embed_adapter,
    run_translate_adapter,
    run_stt_transcribe_adapter,
    run_notify_adapter,
    run_diff_change_adapter,
    run_notes_adapter,
    run_prompts_adapter,
    run_chunking_adapter,
    run_web_search_adapter,
    run_collections_adapter,
    run_chatbooks_adapter,
    run_evaluations_adapter,
    run_claims_extract_adapter,
    run_character_chat_adapter,
    run_moderation_adapter,
    run_sandbox_exec_adapter,
    run_image_gen_adapter,
    run_summarize_adapter,
    run_query_expand_adapter,
    run_rerank_adapter,
    run_citations_adapter,
    run_ocr_adapter,
    run_pdf_extract_adapter,
    run_voice_intent_adapter,
    run_query_rewrite_adapter,
    run_hyde_generate_adapter,
    run_semantic_cache_check_adapter,
    run_search_aggregate_adapter,
    run_entity_extract_adapter,
    run_bibliography_generate_adapter,
    run_document_table_extract_adapter,
    run_audio_diarize_adapter,
    run_flashcard_generate_adapter,
    run_quiz_generate_adapter,
    run_quiz_evaluate_adapter,
    run_outline_generate_adapter,
    run_glossary_extract_adapter,
    run_mindmap_generate_adapter,
    run_eval_readability_adapter,
    run_json_transform_adapter,
    run_json_validate_adapter,
    run_csv_to_json_adapter,
    run_json_to_csv_adapter,
    run_regex_extract_adapter,
    run_text_clean_adapter,
    run_xml_transform_adapter,
    run_template_render_adapter,
    run_batch_adapter,
    run_workflow_call_adapter,
    run_parallel_adapter,
    run_cache_result_adapter,
    run_retry_adapter,
    run_checkpoint_adapter,
    run_s3_upload_adapter,
    run_s3_download_adapter,
    run_github_create_issue_adapter,
    run_llm_with_tools_adapter,
    run_llm_critique_adapter,
    run_context_build_adapter,
    run_document_merge_adapter,
    run_document_diff_adapter,
    run_markdown_to_html_adapter,
    run_html_to_markdown_adapter,
    run_keyword_extract_adapter,
    run_sentiment_analyze_adapter,
    run_language_detect_adapter,
    run_topic_model_adapter,
    run_token_count_adapter,
    run_context_window_check_adapter,
    run_llm_compare_adapter,
    run_image_describe_adapter,
    run_report_generate_adapter,
    run_newsletter_generate_adapter,
    run_slides_generate_adapter,
    run_diagram_generate_adapter,
    run_email_send_adapter,
    run_screenshot_capture_adapter,
    run_schedule_workflow_adapter,
    run_timing_start_adapter,
    run_timing_stop_adapter,
    run_audio_normalize_adapter,
    run_audio_concat_adapter,
    run_audio_trim_adapter,
    run_audio_convert_adapter,
    run_audio_extract_adapter,
    run_audio_mix_adapter,
    run_video_thumbnail_adapter,
    run_video_trim_adapter,
    run_video_concat_adapter,
    run_video_convert_adapter,
    run_video_extract_frames_adapter,
    run_subtitle_generate_adapter,
    run_subtitle_translate_adapter,
    run_subtitle_burn_adapter,
    run_arxiv_search_adapter,
    run_arxiv_download_adapter,
    run_pubmed_search_adapter,
    run_semantic_scholar_search_adapter,
    run_google_scholar_search_adapter,
    run_patent_search_adapter,
    run_doi_resolve_adapter,
    run_reference_parse_adapter,
    run_bibtex_generate_adapter,
    run_literature_review_adapter,
    run_kanban_adapter,
)

__all__ = [
    # Registry
    "registry",
    "get_adapter",
    "get_parallelizable",
    "AdapterSpec",
    "AdapterRegistry",
    # Base types
    "AdapterContext",
    "BaseAdapterConfig",
    "AdapterFunc",
    "AdapterResult",
    # Common utilities
    "extract_openai_content",
    "sanitize_path_component",
    "is_subpath",
    "resolve_context_user_id",
    "artifacts_base_dir",
    "resolve_artifacts_dir",
    "resolve_artifact_filename",
    "unsafe_file_access_allowed",
    "workflow_file_base_dir",
    "resolve_workflow_file_path",
    "resolve_workflow_file_uri",
    "normalize_str_list",
    "extract_mcp_policy",
    "tool_matches_allowlist",
    "extract_tool_scopes",
    "format_time_srt",
    "format_time_vtt",
    # Category modules
    "control",
    "llm",
    "audio",
    "video",
    "media",
    "rag",
    "knowledge",
    "content",
    "text",
    "integration",
    "evaluation",
    "research",
    "utility",
    # Backward-compatible adapter function exports
    "run_llm_adapter",
    "run_prompt_adapter",
    "run_rag_search_adapter",
    "run_media_ingest_adapter",
    "run_mcp_tool_adapter",
    "run_webhook_adapter",
    "run_tts_adapter",
    "run_process_media_adapter",
    "run_branch_adapter",
    "run_map_adapter",
    "run_delay_adapter",
    "run_log_adapter",
    "run_policy_check_adapter",
    "run_rss_fetch_adapter",
    "run_embed_adapter",
    "run_translate_adapter",
    "run_stt_transcribe_adapter",
    "run_notify_adapter",
    "run_diff_change_adapter",
    "run_notes_adapter",
    "run_prompts_adapter",
    "run_chunking_adapter",
    "run_web_search_adapter",
    "run_collections_adapter",
    "run_chatbooks_adapter",
    "run_evaluations_adapter",
    "run_claims_extract_adapter",
    "run_character_chat_adapter",
    "run_moderation_adapter",
    "run_sandbox_exec_adapter",
    "run_image_gen_adapter",
    "run_summarize_adapter",
    "run_query_expand_adapter",
    "run_rerank_adapter",
    "run_citations_adapter",
    "run_ocr_adapter",
    "run_pdf_extract_adapter",
    "run_voice_intent_adapter",
    "run_query_rewrite_adapter",
    "run_hyde_generate_adapter",
    "run_semantic_cache_check_adapter",
    "run_search_aggregate_adapter",
    "run_entity_extract_adapter",
    "run_bibliography_generate_adapter",
    "run_document_table_extract_adapter",
    "run_audio_diarize_adapter",
    "run_flashcard_generate_adapter",
    "run_quiz_generate_adapter",
    "run_quiz_evaluate_adapter",
    "run_outline_generate_adapter",
    "run_glossary_extract_adapter",
    "run_mindmap_generate_adapter",
    "run_eval_readability_adapter",
    "run_json_transform_adapter",
    "run_json_validate_adapter",
    "run_csv_to_json_adapter",
    "run_json_to_csv_adapter",
    "run_regex_extract_adapter",
    "run_text_clean_adapter",
    "run_xml_transform_adapter",
    "run_template_render_adapter",
    "run_batch_adapter",
    "run_workflow_call_adapter",
    "run_parallel_adapter",
    "run_cache_result_adapter",
    "run_retry_adapter",
    "run_checkpoint_adapter",
    "run_s3_upload_adapter",
    "run_s3_download_adapter",
    "run_github_create_issue_adapter",
    "run_llm_with_tools_adapter",
    "run_llm_critique_adapter",
    "run_context_build_adapter",
    "run_document_merge_adapter",
    "run_document_diff_adapter",
    "run_markdown_to_html_adapter",
    "run_html_to_markdown_adapter",
    "run_keyword_extract_adapter",
    "run_sentiment_analyze_adapter",
    "run_language_detect_adapter",
    "run_topic_model_adapter",
    "run_token_count_adapter",
    "run_context_window_check_adapter",
    "run_llm_compare_adapter",
    "run_image_describe_adapter",
    "run_report_generate_adapter",
    "run_newsletter_generate_adapter",
    "run_slides_generate_adapter",
    "run_diagram_generate_adapter",
    "run_email_send_adapter",
    "run_screenshot_capture_adapter",
    "run_schedule_workflow_adapter",
    "run_timing_start_adapter",
    "run_timing_stop_adapter",
    "run_audio_normalize_adapter",
    "run_audio_concat_adapter",
    "run_audio_trim_adapter",
    "run_audio_convert_adapter",
    "run_audio_extract_adapter",
    "run_audio_mix_adapter",
    "run_video_thumbnail_adapter",
    "run_video_trim_adapter",
    "run_video_concat_adapter",
    "run_video_convert_adapter",
    "run_video_extract_frames_adapter",
    "run_subtitle_generate_adapter",
    "run_subtitle_translate_adapter",
    "run_subtitle_burn_adapter",
    "run_arxiv_search_adapter",
    "run_arxiv_download_adapter",
    "run_pubmed_search_adapter",
    "run_semantic_scholar_search_adapter",
    "run_google_scholar_search_adapter",
    "run_patent_search_adapter",
    "run_doi_resolve_adapter",
    "run_reference_parse_adapter",
    "run_bibtex_generate_adapter",
    "run_literature_review_adapter",
    "run_kanban_adapter",
]
